routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
Telas para ver o funcionamento sem dados
*/ 
Route::resource('/', "DashboardController");
Route::resource('/sales',"VendaController");
Route::resource('/products', "ProdutoController");
 

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $table = 'clientes';
    protected $primaryKey = 'id';

    protected $fillable = [
        "nome",
        "email",
        "cpf" 
    ];
    
    protected $guarded  = [
        'id', 'created_at', 'updated_at' 
    ];
}

app/Produto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    protected $table = 'produtos';
    protected $primaryKey = 'id';

    protected $fillable = [
        "nome",
        "descricao", 
        "preco", 
    ];
    
    protected $guarded  = [
        'id', 'created_at', 'updated_at' 
    ];
}

app/StatusVenda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StatusVenda extends Model
{
    protected $table = 'status_vendas';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        "nome"
    ];
    
    protected $guarded  = [
        'id'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Venda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Venda extends Model
{
    protected $table = 'vendas';
    protected $primaryKey = 'id';

    protected $fillable = [
        "produto_id",
        "cliente_id", 
        "quantidade",
        "desconto",
        "status"
    ];
    
    protected $guarded  = [
        'id', 'created_at', 'updated_at' 
    ];
    
    /*
     * 
     */
    static public function listaVendas(){
        $qry = DB::select("SELECT A.id, B.nome, ((B.preco * A.quantidade) - A.desconto) AS valor, DATE_FORMAT(A.created_at,'%d/%m/%Y %Hh%i') AS data
                            FROM vendas AS A  
                            LEFT JOIN produtos AS B ON(A.produto_id = B.id)");
        return $qry;
    }
    
    /*
     * 
     */
    static public function totalizadorVendas(){
        $qry = DB::select("SELECT nome, SUM(qnt) AS qnt, SUM(prc) AS prc FROM (  
                                    SELECT B.nome, (A.quantidade) AS qnt, ((A.quantidade * C.preco) - A.desconto) AS prc
                                FROM vendas AS A  
                              LEFT JOIN status_vendas AS B ON(A.status = B.id)
                              LEFT JOIN produtos AS C ON(A.produto_id = C.id)
                            ) AS tmp GROUP BY nome");
        return $qry;
        
    }
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cliente;

class ClienteController extends Controller
{
    public function index(Request $request){
        
        
        
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cliente;
use App\Venda;
use App\Produto;

class DashboardController extends Controller {

    public function index(Request $request) {
        /**
         * LISTA DE CLIENTES
         */
        $clientes = Cliente::all();

        /*
         * 
         */
        $vendas = Venda::listaVendas();
        
        /*
         * 
         */
        $totalizador = Venda::totalizadorVendas();
        
        /*
         * 
         */
        $produtos = Produto::all();
         
        return view("dashboard", ["clientes" => $clientes, "vendas" => $vendas, "totalizador" => $totalizador, "produtos" => $produtos]);
        
    }

}

app/Http/Controllers/ProdutoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Produto;

class ProdutoController extends Controller
{
    
    public function create(Request $request){
        
         
        return view('crud_products');
        
    }
    
    /*
     * 
     */
    public function store(Request $request)
    {
         
        $produto = [
            "nome" => $request->nome,
            "descricao" => $request->descricao,
            "preco" => $request->preco 
        ];
        
        Produto::create($produto);
        
        return redirect('/');
     
    }
    
    /**
     * 
     * @param Request $request
     */
    public function edit(Request $request, $id){
        
        
        $produto = Produto::where("id","=",$id)->get()[0];
         
        return view('crud_products',["produto" => $produto]);
        
    }
    
    /*
     * 
     */
    public function update(Request $request, $id){
        
        $produto = Produto::findOrFail($id); 
        $produto->nome    = $request->nome;
        $produto->descricao    = $request->descricao; 
        $produto->preco    = $request->preco;  
         
        $produto->save();
        
        return redirect('/');
        
    }
}

app/Http/Controllers/VendaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Venda;
use App\Cliente;
use App\Produto;

class VendaController extends Controller
{
    
    public function create(Request $request){
        
        $produtos = Produto::all();
        $clientes = Cliente::all();
        
        return view('crud_sales',["produtos" => $produtos, "clientes" => $clientes]);
        
    }
    
    /*
     * 
     */
    public function store(Request $request)
    {
         
        $venda = [
            "produto_id" => $request->product,
            "cliente_id" => $request->cliente,
            "quantidade" => $request->quantidade,
            "desconto" => number_format($request->desconto,2,'.',''),
            "status" => $request->status
        ];
        
        Venda::create($venda);
        
        return redirect('/');
     
    }
    
    /**
     * 
     * @param Request $request
     */
    public function edit(Request $request, $id){
        
        $produtos = Produto::all();
        $clientes = Cliente::all();
        $venda = Venda::where("id","=",$id)->get()[0];
         
        return view('crud_sales',["produtos" => $produtos, "clientes" => $clientes, "venda" => $venda]);
        
    }
    
    /*
     * 
     */
    public function update(Request $request, $id){
        
        $venda = Venda::findOrFail($id); 
        $venda->produto_id    = $request->product;
        $venda->cliente_id    = $request->cliente; 
        $venda->quantidade    = $request->quantidade; 
        $venda->desconto      = $request->desconto; 
        $venda->status        = $request->status; 
         
        $venda->save();
        
        return redirect('/');
        
    }
    
    /*
     * 
     */
    public function destroy(Request $request, $id){
         
        $venda = Venda::findOrFail($id);
        $venda->delete();
        return redirect('/');
        
    }
}

resources/views/crud_products.blade.php
@extends('layout')

@section('content')
    <h1>{{ isset($produto['id'])?'Editar Produto':'Adicionar' }}</h1>
    <div class='card'>
        <div class='card-body'>
            <form action='{{ (!empty($produto['id'])) ? "/products/{$produto['id']}" : route('products.store') }}' method="post">
                
                @csrf
                
                @if(!empty($produto))
                    @method('PUT')
                @endif
                
                <div class="form-group">
                    <label for="nome">Nome do produto</label>
                    <input type="text" class="form-control "  value="{{ !empty($produto['nome'])?$produto['nome']:"" }}" name="nome">
                </div>
                <div class="form-group">
                    <label for="descricao">Descrição</label>
                    <textarea type="text" rows='5' class="form-control" name="descricao">{{ !empty($produto['descricao'])?$produto['descricao']:"" }}</textarea>
                </div>
                <div class="form-group">
                    <label for="preco">Preço</label>
                    <input type="text" class="form-control" name="preco"  value="{{ !empty($produto['preco'])?$produto['preco']:"" }}" placeholder="100,00 ou maior">
                </div>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
    </div>
@endsection

resources/views/crud_sales.blade.php
@extends('layout')

@section('content')
    <h1> {{ isset($venda['id'])?'Editar Venda':'Adicionar' }}</h1>
    <div class='card'>
        <div class='card-body'>
            <form action="{{ (!empty($venda['id'])) ? "/sales/{$venda['id']}" : route('sales.store') }}" method="POST">
                @csrf
                
                @if(!empty($venda))
                    @method('PUT')
                @endif
                        
                <h5>Informações do cliente</h5>
                <div class="form-group">
                    <label for="cliente">Cliente</label>
                    <select name="cliente" class="form-control">
                        <option selected>Escolha...</option>
                        @foreach($clientes as $cliente)
                                
                            <option value="{{ $cliente->id }}" {{ (!empty($venda) && $cliente->id == $venda['cliente_id'])?"selected":"" }}>{{ $cliente->nome }}</option>
                        @endforeach
                    </select>
                </div>
                <h5 class='mt-5'>Informações da venda</h5>
                <div class="form-group">
                    <label for="product">Produto</label>
                    <select name="product" class="form-control">
                        <option selected>Escolha...</option>
                        @foreach($produtos as $produto)
                            <option value="{{ $produto->id }}"  {{ (!empty($venda) && $produto->id == $venda['produto_id'])?"selected":"" }}>{{ $produto->nome }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="quantity">Quantidade</label>
                    <input type="text" class="form-control" name="quantidade" value="{{ !empty($venda['quantidade'])?$venda['quantidade']:"" }}" placeholder="1 a 10">
                </div>
                <div class="form-group">
                    <label for="discount">Desconto</label>
                    <input type="text" class="form-control" name="desconto" value="{{ !empty($venda['desconto'])?$venda['desconto']:"" }}" placeholder="100,00 ou menor">
                </div>
                <div class="form-group">
                    <label for="status">Status</label>
                    <select name="status" class="form-control">
                        <option {{ (!empty($venda))?"":"selected" }}>Escolha...</option>
                        <option value="1" {{ (!empty($venda) && $venda['status']== 1)?"selected":"" }}>Vendidos</option> 
                        <option value="2" {{ (!empty($venda) && $venda['status']== 2)?"selected":""  }}>Devolvido</option>
                        <option value="3" {{ (!empty($venda) && $venda['status']== 3)?"selected":""  }}>Cancelados</option>
                    </select>
                </div>
                <input type="hidden" name="id" value="{{ !empty($venda['id'])?$venda['id']:"" }}" />
                <button type="submit" class="btn btn-primary">{{ !empty($venda['id'])?"Editar":"Salvar" }}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/dashboard.blade.php
@extends('layout')

@section('content')
    <h1>Dashboard de vendas</h1>
    <div class='card mt-3'>
        <div class='card-body'>
            <h5 class="card-title mb-5">Tabela de vendas
                <a href='{{ url("/sales/create") }}' class='btn btn-secondary float-right btn-sm rounded-pill'><i class='fa fa-plus'></i>  Nova venda</a></h5>
            <form>
                <div class="form-row align-items-center">
                    <div class="col-sm-5 my-1">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">Clientes</div>
                            </div>
                            <select class="form-control" id="inlineFormInputName">
                                @foreach($clientes as $cliente)
                                    <option value="{{ $cliente->id }}">{{ $cliente->nome }}</option> 
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6 my-1">
                        <label class="sr-only" for="inlineFormInputGroupUsername">Username</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">Período</div>
                            </div>
                            <input type="text" class="form-control date_range" id="inlineFormInputGroupUsername" placeholder="Username">
                        </div>
                    </div>
                    <div class="col-sm-1 my-1">
                        <button type="submit" class="btn btn-primary" style='padding: 14.5px 16px;'>
                            <i class='fa fa-search'></i></button>
                    </div>
                </div>
            </form>
            <table class='table'>
                <tr>
                    <th scope="col">
                        Produto
                    </th>
                    <th scope="col">
                        Data
                    </th>
                    <th scope="col">
                        Valor
                    </th>
                    <th colspan="2" scope="col">
                        Ações
                    </th>
                </tr>
                @foreach($vendas as $venda)
                    <tr>
                        <td>
                            {{ $venda->nome }}
                        </td>
                        <td>
                            {{ $venda->data }}
                        </td>
                        <td>
                           R$ {{ number_format($venda->valor,2,',','.') }}
                        </td>
                        <td>
                            <a href='{{ url("/sales/{$venda->id}/edit") }}' class='btn btn-primary'>Editar</a>
                        </td> 
                        <td>
                            <form action="sales/{{ $venda->id }} " method="post">
                                
                                @csrf  
                                @method('delete')
                                <input type="submit" class='btn btn-danger'  value="Deletar" />
                            </form>
                        </td> 
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
    <div class='card mt-3'>
        <div class='card-body'>
            <h5 class="card-title mb-5">Resultado de vendas</h5>
            <table class='table'>
                <tr>
                    <th scope="col">
                        Status
                    </th>
                    <th scope="col">
                        Quantidade
                    </th>
                    <th scope="col">
                        Valor Total
                    </th>
                </tr>
                @foreach($totalizador as $total)
                <tr>
                    <td>
                        {{ $total->nome }}
                    </td>
                    <td>
                        {{ $total->qnt }}
                    </td>
                    <td>
                       R$ {{ number_format($total->prc,2,',','.') }}
                    </td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>

    <div class='card mt-3'>
        <div class='card-body'>
            <h5 class="card-title mb-5">Produtos
                <a href='{{ url("/products/create") }}' class='btn btn-secondary float-right btn-sm rounded-pill'><i class='fa fa-plus'></i>  Novo produto</a></h5>
            <table class='table'>
                <tr>
                    <th scope="col">
                        Nome
                    </th>
                    <th scope="col">
                        Valor
                    </th>
                    <th scope="col">
                        Ações
                    </th>
                </tr>
                @foreach($produtos as $produto)
                <tr>
                    <td>
                        {{ $produto->nome }}
                    </td>
                    <td>
                       R$ {{ number_format($produto->preco,2,',','.') }}
                    </td>
                    <td>
                        <a href='{{ url("/products/{$produto->id}/edit") }}' class='btn btn-primary'>Editar</a>
                    </td>
                </tr> 
                @endforeach
            </table>
        </div>
    </div>
@endsection

resources/views/layout.blade.php
<html lang='pt-br'>
<head>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <title>Perfect Pay - Teste - @yield('title')</title>
    <link href="{{ asset('/images/brand/favicon.png') }}" rel="icon" type="image/png"/>
    <link rel='stylesheet' href="{{ url('/css/app.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap" rel="stylesheet">
    <style>
        .wrapper #wrapperContent, .wrapper #wrapperContent.closed {
            padding: 0;
        }
    </style>
</head>
<body>
<!-- NAVBAR TOP -->
@include('layout_header')
<div class='wrapper'>
    <div id='wrapperContent' class='content container-fluid'>
        <div id='main'>
            @yield('content')
        </div>
    </div>
</div>
<script src="{{ url('/js/app.js') }}"></script>
<script src="https://kit.fontawesome.com/d712964458.js" crossorigin="anonymous"></script>
@yield('script')
</body>
</html>

resources/views/layout_header.blade.php
<nav class="navbar bg-gradient-primary" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand -->
        <a class="" href="{{ url('/') }}">Teste Back End</a>
        <!-- User -->
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a id="bell" class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-bell"></i>
                    <span id="bell-number" class="badge badge-danger badge-pill"></span>
                </a>
                <div id='notifications' class="dropdown-menu dropdown-menu-right position-absolute" aria-labelledby="navbar-default_dropdown_1">
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class='d-md-down-none'>Albert Einsten</span>
                    <img class='rounded-pill' src='{{ url("/img/destaque-albert-einstein.jpg") }}' width='40' height='40' alt='Albert Einsten'>
                </a>
                <div class="dropdown-menu dropdown-menu-right position-absolute">
                    <div class="dropdown-header">
                        <h6 class="text-overflow m-0">Bem vindo(a)!</h6>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</nav>